### ISSUE TITLE
Changing a Single X, Multiple Y plot to a different type and back to SiX,MuY messes up the graph

### ISSUE THREAD

**Issue by rtapella** [NASA-AMMOS/CODEX#54]
1. make Single X Multiple Y
![Screen Shot 2022-11-23 at 12.23.16 PM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/796bbe09-4720-40dc-91bf-3e7c820df3ee)

2. change type to time series (or other thing)
![Screen Shot 2022-11-23 at 12.23.40 PM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/0f98a03d-0391-4273-a0e7-0f4c8736a376)

3. messed up
![Screen Shot 2022-11-23 at 12.22.33 PM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/963b789e-8f14-4609-821b-61fdb8336d32)

**Comment by jdrodjpl** [comment]
fix pushed to develop
