### ISSUE TITLE
Explain This tree-depth selection bar is wrong length

### ISSUE THREAD

**Issue by rtapella** [NASA-AMMOS/CODEX#56]
The tree-depth slider in the Explain This workflow should match up with the x-axis of the plot above it

![Screen Shot 2022-12-19 at 11.34.04 AM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/3a824181-1bdc-4241-8578-73a5e7fe9b17)

**Comment by jdrodjpl** [comment]
fix pushed to develop
